### ISSUE TITLE
How do i set the VIDIT dataset?

### ISSUE THREAD

**Issue by P66094125** [rpautrat/LISRD#11]
hi~The following is my error warning.

[09/03/2021 10:30:01 INFO] Running command TRAIN
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Desktop\python\STUDY_CNN_imagematching\LISRD-master\lisrd\experiment.py", line 130, in <module>
    args.func(config, exper_dir, args)
  File "C:\Users\User\Desktop\python\STUDY_CNN_imagematching\LISRD-master\lisrd\experiment.py", line 39, in _train
    config['data']['name'])(config['data'], device)
  File "C:\Users\User\Desktop\python\STUDY_CNN_imagematching\LISRD-master\lisrd\datasets\mixed_dataset.py", line 32, in __init__
    device))
  File "C:\Users\User\Desktop\python\STUDY_CNN_imagematching\LISRD-master\lisrd\datasets\vidit.py", line 27, in __init__
    files = np.sort(files).reshape(300, 40)
ValueError: cannot reshape array of size 11999 into shape (300,40)

![image](https://user-images.githubusercontent.com/75246176/131941803-4f8b0305-e82a-470f-949c-0404df854c60.png)
here are many datasets, which dataset is suitable for use?
And what should the folder structure be?

**Comment by rpautrat** [comment]
Hi, the train dataset of track 2 with the original file structure should be the right one (i.e. all images in the same folder).

But apparently you only have 11999 images instead of the 12000 that are expected. Maybe something went wrong when downloading the dataset? I recommend you to try again to download it and check that you get 12000 images.

**Comment by P66094125** [comment]
Thank you for your reply.
